### ISSUE TITLE
Wrong site in your post

### ISSUE THREAD

**Issue by yangsibai** [ptmt/ptmt.github.com#2]
In the post: http://potomushto.com/2015/01/26/facebook-flow-on-server-and-client.html, there is a link to **tryflow dot org**, it's a porn site, do you mean <https://flow.org/try/> .

**Comment by ptmt** [comment]
There was a project https://github.com/ptmt/tryflow which was very similar and created a year before flow.org/try/ but now it's an obsolete and the domain went to wrong people. Thanks for pointing out, I'll edit all links.
